apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: l2c-deploy
spec:
  params:
    - description: Deployment name
      name: app-name
      type: string
    - description: Updated image url:tag
      name: image-url
      type: string
    - default: ""
      description: Deployment configmap name
      name: deploy-cfg-name
      type: string
    - default: '{}'
      description: Deployment environment variable in JSON object form
      name: deploy-env-json
      type: string
  steps:
    - args:
        - make-deployment
      env:
        - name: APP_NAME
          value: $(inputs.params.app-name)
        - name: IMAGE_URL
          value: $(inputs.params.image-url)
        - name: CONFIGMAP_NAME
          value: $(inputs.params.deploy-cfg-name)
        - name: DEPLOY_ENV_JSON
          value: $(inputs.params.deploy-env-json)
      image: tmaxcloudck/cicd-util:latest
      imagePullPolicy: Always
      name: create-yaml
      resources: {}
      volumeMounts:
        - mountPath: /generate
          name: generate
    - args:
        - apply
        - -f
        - /generate/deployment.yaml
      command:
        - kubectl
      image: tmaxcloudck/cicd-util:latest
      name: run-kubectl
      resources: {}
      volumeMounts:
        - mountPath: /generate
          name: generate
  volumes:
    - emptyDir: {}
      name: generate
