apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: l2c-sonar-scan-java-maven
spec:
  description: Sonar scan task for Java Maven projects
  params:
    - name: sonar-url
      description: Sonar Qube server URL
    - name: sonar-token
      description: Token for sonar qube
    - name: sonar-project-id
      description: Project ID in sonar qube
  resources:
    inputs:
      - name: git-source
        type: git
  steps:
    - name: build-and-scan
      image: maven:3.3
      imagePullPolicy: Always
      script: |
        mvn clean verify sonar:sonar -Dsonar.host.url=$(params.sonar-url) -Dsonar.login=$(params.sonar-token) -Dsonar.projectKey=$(params.sonar-project-id)
      workingDir: /workspace/git-source
    - name: waiter
      image: tmaxcloudck/l2c-scan-waiter:v0.0.1
      imagePullPolicy: Always
      command:
        - /scan-waiter
        - wait
