apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tupdbs.tmax.io
spec:
  group: tmax.io
  names:
    kind: TupDB
    listKind: TupDBList
    plural: tupdbs
    singular: tupdb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: TupDB is the Schema for the tupdbs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TupDBSpec defines the desired state of TupDB
          properties:
            from:
              description: DB Source configuration
              properties:
                host:
                  description: Current DB host
                  pattern: (([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])
                  type: string
                password:
                  description: Current DB password
                  type: string
                port:
                  description: Current DB port
                  format: int32
                  type: integer
                sid:
                  description: Current DB SID
                  type: string
                type:
                  description: Current DB Type
                  enum:
                  - oracle
                  type: string
                user:
                  description: Current DB user
                  type: string
              type: object
            to:
              description: DB destination configuration
              properties:
                password:
                  description: Password for target DB
                  type: string
                sid:
                  description: Current DB SID
                  type: string
                storageSize:
                  description: Storage size of target DB
                  type: string
                type:
                  description: Target DB type, to be migrated
                  enum:
                  - tibero
                  type: string
                user:
                  description: User for target DB
                  type: string
              type: object
          required:
          - from
          - to
          type: object
        status:
          description: TupDBStatus defines the observed state of TupDB
          properties:
            conditions:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            lastAnalyzeResult:
              type: string
            targetHost:
              description: Target DB host
              pattern: (([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])
              type: string
            targetPort:
              description: Current DB port
              format: int32
              type: integer
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
