apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.l2crun.tmax.io
spec:
  group: l2crun.tmax.io
  groupPriorityMinimum: 100
  service:
    name: l2c-operator
    namespace: l2c-system
    port: 24335
  version: v1
  versionPriority: 100
