apiVersion: apps/v1
kind: Deployment
metadata:
  name: l2c-operator
  namespace: l2c-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: l2c-operator
  template:
    metadata:
      labels:
        name: l2c-operator
    spec:
      serviceAccountName: l2c-operator
      containers:
        - name: l2c-operator
          image: 172.22.11.2:30500/l2c-operator:v0.0.1
          command:
          - l2c-operator
          - --storageClassName=csi-cephfs-sc
          - --sonarQubeImage=azssi/working:0.0.1
          - --editorImage=192.168.6.110:5000/tmax/code-server:3.3.1
          - --builderImageJeus=192.168.6.110:5000/s2i-jeus:8
          - --encryptKey=l2c-operator-salt-12333
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "l2c-operator"
